### ISSUE TITLE
Can you update the router based on the latest version?

### ISSUE THREAD

**Issue by coolsnake** [Korijn/flexxtodo#1]
Hi, Korijn

Can you update the router based on the latest version?

https://github.com/flexxui/flexx/issues/182

Thanks.

**Comment by Korijn** [comment]
Sorry, I'm no longer working on this.

**Comment by coolsnake** [comment]
May I know any other alternative you are using now? I like flexx, but it is not mature.

**Comment by Korijn** [comment]
@almarklein I think your users want a router! :)

Alternative GUI library? I like pyside2. Otherwise, if you want to use web technology, just go with Electron.

**Comment by coolsnake** [comment]
Thanks. 
I found another one. It looks good.
https://github.com/dddomodossola/remi
